# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: raviraj.rjgallery::lang.idgallery.title

# Model Form Field configuration
form: $/raviraj/rjgallery/models/gallery/fields.yaml

# Model Class name
modelClass: Raviraj\Rjgallery\Models\Gallery

# Default redirect location
defaultRedirect: raviraj/rjgallery/galleries

# Create page
create:
    title: raviraj.rjgallery::lang.form.create
    redirect: raviraj/rjgallery/galleries/update/:id
    redirectClose: raviraj/rjgallery/galleries

# Update page
update:
    title: raviraj.rjgallery::lang.form.update
    redirect: raviraj/rjgallery/galleries
    redirectClose: raviraj/rjgallery/galleries

# Preview page
preview:
    title: raviraj.rjgallery::lang.form.preview